### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by elbaulp** [adriennefriend/imposter-syndrome-disclaimer#1]
Hi, I wanted to learn more about what this project is about. In your README you say:

> you can read here (link).

But there is no link. Could you provide it, please?

Bests

**Comment by adriennefriend** [comment]
Hello @elbaulp ! Great question.

The point is that _you_ would provide the link to your project's own Contribution Guidelines.

Contribution Guidelines are strongly recommended and every project writes them differently.

You can see some examples here:

- [BeeWare Project](https://pybee.org/), [contribution guidelines](https://pybee.org/contributing/how/first-time/)
- [Cyrus IMAP](https://www.cyrusimap.org/index.html) [Contributor Guide](https://www.cyrusimap.org/imap/developer.html#imap-developer)
- [MetPy](https://github.com/Unidata/MetPy) [contributing documentation](https://github.com/Unidata/MetPy/blob/master/CONTRIBUTING.md).

If your project doesn't have Contribution Guidelines, you could simply delete this sentence.

If you do have them, you would link to them.

Hope that helps! Let me know if you have other questions. 😄

**Comment by elbaulp** [comment]
Ohh, I see, so this is like a template to include in your projects. Thanks!
